// 模板管理器
// 注意：在 Node.js 环境中运行，不使用 DOM API

/**
 * 模板类型
 */
export enum TemplateType {
  BENTO = 'bento',
  NEWSLETTER = 'newsletter',
  RETRO_LETTER = 'retro_letter',
}

/**
 * 模板数据
 */
export interface TemplateData {
  conversationId: number;
  platform: string;
  socialMediaSummary?: string;
  detailedSummary?: string;
  messageCount: number;
  capturedAt: string;
  imageUrl?: string;
}

/**
 * HTML 模板接口
 */
export interface HTMLTemplate {
  name: string;
  description: string;
  generateHTML: (data: TemplateData) => string;
}

/**
 * Bento UI 模板（网格布局）
 */
export class BentoTemplate implements HTMLTemplate {
  name = 'Bento UI';
  description = '现代网格布局，适合社交媒体分享';

  generateHTML(data: TemplateData): string {
    const platformIcon = this.getPlatformIcon(data.platform);
    const date = new Date(data.capturedAt).toLocaleDateString('zh-CN');

    return `
<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>AI Chat - ${data.conversationId}</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      display: flex;
      justify-content: center;
      align-items: center;
      min-height: 100vh;
      padding: 40px;
    }

    .bento-grid {
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      grid-template-rows: auto auto auto;
      gap: 16px;
      max-width: 900px;
      width: 100%;
    }

    .card {
      background: white;
      border-radius: 24px;
      padding: 32px;
      box-shadow: 0 20px 60px rgba(0, 0, 0, 0.15);
    }

    .card-header {
      grid-column: 1 / -1;
      display: flex;
      justify-content: space-between;
      align-items: center;
    }

    .platform-badge {
      display: flex;
      align-items: center;
      gap: 12px;
      font-size: 24px;
      font-weight: 700;
      color: #667eea;
    }

    .conversation-id {
      font-size: 16px;
      color: #999;
    }

    .card-main {
      grid-column: 1 / -1;
    }

    .summary {
      font-size: 20px;
      line-height: 1.6;
      color: #333;
      white-space: pre-wrap;
    }

    .card-meta {
      grid-column: 1 / 2;
      display: flex;
      flex-direction: column;
      gap: 8px;
    }

    .meta-item {
      display: flex;
      flex-direction: column;
      gap: 4px;
    }

    .meta-label {
      font-size: 12px;
      color: #999;
      text-transform: uppercase;
      letter-spacing: 1px;
    }

    .meta-value {
      font-size: 18px;
      font-weight: 600;
      color: #333;
    }

    .card-image {
      grid-column: 2 / -1;
      background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%);
      border-radius: 16px;
      min-height: 150px;
      display: flex;
      justify-content: center;
      align-items: center;
      color: white;
      font-size: 48px;
    }

    .watermark {
      grid-column: 1 / -1;
      text-align: center;
      font-size: 14px;
      color: #999;
      padding-top: 16px;
    }
  </style>
</head>
<body>
  <div class="bento-grid">
    <div class="card card-header">
      <div class="platform-badge">
        <span>${platformIcon}</span>
        <span>${data.platform}</span>
      </div>
      <div class="conversation-id">#${data.conversationId}</div>
    </div>

    <div class="card card-main">
      <div class="summary">${this.escapeHtml(data.socialMediaSummary || '暂无摘要')}</div>
    </div>

    <div class="card card-meta">
      <div class="meta-item">
        <span class="meta-label">日期</span>
        <span class="meta-value">${date}</span>
      </div>
      <div class="meta-item">
        <span class="meta-label">消息数</span>
        <span class="meta-value">${data.messageCount} 条</span>
      </div>
    </div>

    ${data.imageUrl ? `
    <div class="card card-image">
      📷
    </div>
    ` : ''}

    <div class="watermark">
      Generated by AI Chat Extractor
    </div>
  </div>
</body>
</html>
    `.trim();
  }

  private getPlatformIcon(platform: string): string {
    const icons: Record<string, string> = {
      Gemini: '✨',
      Doubao: '🫘',
    };
    return icons[platform] || '🤖';
  }

  private escapeHtml(text: string): string {
    return text
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#039;');
  }
}

/**
 * Newsletter 模板（邮件风格）
 */
export class NewsletterTemplate implements HTMLTemplate {
  name = 'Newsletter';
  description = '邮件风格，适合分享给订阅者';

  generateHTML(data: TemplateData): string {
    const date = new Date(data.capturedAt).toLocaleDateString('zh-CN');

    return `
<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>AI Chat Digest - ${date}</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Georgia', serif;
      background: #f5f5f5;
      padding: 40px 20px;
    }

    .container {
      max-width: 600px;
      margin: 0 auto;
      background: white;
      border-radius: 12px;
      overflow: hidden;
      box-shadow: 0 4px 20px rgba(0, 0, 0, 0.08);
    }

    .header {
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      color: white;
      padding: 40px;
      text-align: center;
    }

    .header h1 {
      font-size: 32px;
      margin-bottom: 8px;
    }

    .header .subtitle {
      font-size: 14px;
      opacity: 0.9;
    }

    .content {
      padding: 40px;
    }

    .meta {
      display: flex;
      justify-content: space-between;
      padding-bottom: 20px;
      border-bottom: 2px solid #f0f0f0;
      margin-bottom: 20px;
      font-size: 12px;
      color: #999;
    }

    .summary {
      font-size: 16px;
      line-height: 1.8;
      color: #333;
      white-space: pre-wrap;
    }

    .footer {
      background: #f9f9f9;
      padding: 20px;
      text-align: center;
      font-size: 12px;
      color: #999;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>AI Chat Digest</h1>
      <div class="subtitle">每日精选 AI 对话摘要</div>
    </div>

    <div class="content">
      <div class="meta">
        <span>📅 ${date}</span>
        <span>💬 ${data.messageCount} 条消息</span>
        <span>🤖 ${data.platform}</span>
      </div>

      <div class="summary">${this.escapeHtml(data.socialMediaSummary || '暂无摘要')}</div>
    </div>

    <div class="footer">
      Generated by AI Chat Extractor • Conversation #${data.conversationId}
    </div>
  </div>
</body>
</html>
    `.trim();
  }

  private escapeHtml(text: string): string {
    return text
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#039;');
  }
}

/**
 * 复古信纸模板
 */
export class RetroLetterTemplate implements HTMLTemplate {
  name = 'Retro Letter';
  description = '复古信纸风格，温馨怀旧';

  generateHTML(data: TemplateData): string {
    const date = new Date(data.capturedAt).toLocaleDateString('zh-CN');

    return `
<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Letter - ${data.conversationId}</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Caveat:wght@400;700&family=Noto+Serif+SC:wght@400;700&display=swap');

    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body {
      font-family: 'Noto Serif SC', serif;
      background: #f4e4bc;
      background-image:
        repeating-linear-gradient(0deg, transparent, transparent 29px, rgba(139, 69, 19, 0.1) 30px);
      padding: 60px 40px;
      min-height: 100vh;
    }

    .paper {
      max-width: 700px;
      margin: 0 auto;
      background: #fffef0;
      padding: 60px;
      box-shadow: 0 0 40px rgba(0, 0, 0, 0.1);
      position: relative;
    }

    .paper::before {
      content: '';
      position: absolute;
      top: 0;
      left: 60px;
      right: 0;
      bottom: 0;
      border-left: 2px solid rgba(255, 0, 0, 0.2);
    }

    .header {
      text-align: center;
      margin-bottom: 40px;
      padding-left: 20px;
    }

    .header h1 {
      font-family: 'Caveat', cursive;
      font-size: 48px;
      color: #8b4513;
      margin-bottom: 8px;
    }

    .header .meta {
      font-size: 14px;
      color: #999;
      font-style: italic;
    }

    .content {
      padding-left: 40px;
      line-height: 2;
    }

    .summary {
      font-size: 16px;
      color: #333;
      white-space: pre-wrap;
    }

    .footer {
      margin-top: 40px;
      padding-left: 40px;
      font-size: 12px;
      color: #999;
      font-style: italic;
    }
  </style>
</head>
<body>
  <div class="paper">
    <div class="header">
      <h1>To: My Future Self</h1>
      <div class="meta">
        📅 ${date} • 💬 ${data.messageCount} 条消息 • 🤖 ${data.platform}
      </div>
    </div>

    <div class="content">
      <div class="summary">${this.escapeHtml(data.socialMediaSummary || '暂无摘要')}</div>
    </div>

    <div class="footer">
      — Generated by AI Chat Extractor (#${data.conversationId})
    </div>
  </div>
</body>
</html>
    `.trim();
  }

  private escapeHtml(text: string): string {
    return text
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#039;');
  }
}

/**
 * 模板管理器
 */
export class TemplateManager {
  private templates: Map<TemplateType, HTMLTemplate>;

  constructor() {
    this.templates = new Map<TemplateType, HTMLTemplate>([
      [TemplateType.BENTO, new BentoTemplate()],
      [TemplateType.NEWSLETTER, new NewsletterTemplate()],
      [TemplateType.RETRO_LETTER, new RetroLetterTemplate()],
    ]);
  }

  /**
   * 获取模板
   */
  getTemplate(type: TemplateType): HTMLTemplate {
    const template = this.templates.get(type);
    if (!template) {
      throw new Error(`Template not found: ${type}`);
    }
    return template;
  }

  /**
   * 列出所有模板
   */
  listTemplates(): Array<{ type: TemplateType; name: string; description: string }> {
    return Array.from(this.templates.entries()).map(([type, template]) => ({
      type,
      name: template.name,
      description: template.description,
    }));
  }
}

/**
 * 模板管理器单例
 */
let templateManagerInstance: TemplateManager | null = null;

export function getTemplateManager(): TemplateManager {
  if (!templateManagerInstance) {
    templateManagerInstance = new TemplateManager();
  }
  return templateManagerInstance;
}

/**
 * 获取模板（便捷方法）
 */
export function getTemplate(type: TemplateType): HTMLTemplate {
  return getTemplateManager().getTemplate(type);
}
